repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.8
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.17.1
  hooks:
    - id: mypy

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.100.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_tflint
#    - id: terraform_checkov
